import React from 'react';
import { 
  MessageSquare, 
  Code, 
  Settings, 
  Files, 
  Play, 
  ChevronRight, 
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  MoveDown,
  MoveUp,
  ArrowLeftToLine,
  ArrowRightToLine,
  Menu,
  Send, 
  User, 
  Terminal,
  Search,
  Plus,
  Copy,
  Check,
  Trash2,
  Edit3,
  Undo2,
  Redo2,
  ClipboardPaste,
  History,
  Save,
  RefreshCw,
  Maximize2,
  FolderOpen,
  ArrowUp,
  Wand2,
  Sparkles,
  Hash,
  Bug,
  FileText,
  Loader2,
  Users,
  Activity,
  Cpu,
  Zap,
  Box,
  Paperclip,
  HelpCircle,
  Image as ImageIcon,
  FileCode,
  FileJson,
  File,
  ChevronDown as ChevronDownIcon,
  ChevronRight as ChevronRightIcon,
  MoreVertical,
  Palette,
  Cog,
  MessageCircle,
  Folder,
  PlayCircle,
  SearchCode,
  Users2,
  User2,
  SquareTerminal,
  PlusSquare,
  Trash,
  Edit,
  CheckCircle,
  SaveAll,
  RefreshCcw,
  Maximize,
  FolderClosed,
  ArrowUpCircle,
  Wand,
  Sparkle,
  BugPlay,
  FileCode2,
  FileJson2,
  MoreHorizontal,
  Code2,
  CheckCircle2,
  Grid3X3,
  ShieldCheck,
  X,
  Bell,
  GitBranch,
  Key,
  Lock,
  CheckCheck,
  Mic,
  Square,
  Pause,
  Video,
  Download
} from 'lucide-react';

export const Codicon = ({ name, size = 16, className = "" }: { name: string; size?: number; className?: string }) => (
  <i 
    className={`codicon codicon-${name} ${className}`} 
    style={{ 
      fontSize: size, 
      display: 'inline-flex', 
      alignItems: 'center', 
      justifyContent: 'center',
      width: size,
      height: size,
      verticalAlign: 'middle'
    }} 
  />
);

export const MaterialIcon = ({ name, size = 16, className = "" }: { name: string; size?: number; className?: string }) => (
  <span 
    className={`material-symbols-outlined ${className}`} 
    style={{ 
      fontSize: size, 
      display: 'inline-flex', 
      alignItems: 'center', 
      justifyContent: 'center',
      width: size,
      height: size,
      verticalAlign: 'middle'
    }}
  >
    {name}
  </span>
);

const GOOGLE_ICON_MAP: Record<string, string> = {
  MessageSquare: 'chat',
  Code: 'code',
  Settings: 'settings',
  Files: 'folder',
  Play: 'play_arrow',
  ChevronRight: 'chevron_right',
  ChevronLeft: 'chevron_left',
  ChevronDown: 'expand_more',
  ChevronUp: 'expand_less',
  Send: 'send',
  User: 'person',
  Terminal: 'terminal',
  Search: 'search',
  Plus: 'add',
  Copy: 'content_copy',
  Check: 'check',
  Trash2: 'delete',
  Edit3: 'edit',
  Undo2: 'undo',
  Redo2: 'redo',
  ClipboardPaste: 'content_paste',
  History: 'history',
  Save: 'save',
  RefreshCw: 'refresh',
  Maximize2: 'fullscreen',
  FolderOpen: 'folder_open',
  ArrowUp: 'arrow_upward',
  Wand2: 'auto_fix_high',
  Sparkles: 'auto_awesome',
  Hash: 'tag',
  Bug: 'bug_report',
  FileText: 'description',
  Loader2: 'progress_activity',
  Users: 'group',
  Paperclip: 'attachment',
  HelpCircle: 'help',
  ImageIcon: 'image',
  FileCode: 'source',
  FileJson: 'data_object',
  File: 'draft',
  MoreVertical: 'more_vert',
  Palette: 'palette',
  Cog: 'settings',
  SearchCode: 'search_check',
  Users2: 'group_add',
  SquareTerminal: 'terminal',
  PlusSquare: 'add_box',
  Trash: 'delete',
  Edit: 'edit',
  CheckCircle: 'check_circle',
  SaveAll: 'save_as',
  RefreshCcw: 'refresh',
  Maximize: 'fullscreen',
  FolderClosed: 'folder',
  ArrowUpCircle: 'arrow_circle_up',
  Wand: 'magic_button',
  Sparkle: 'spark',
  BugPlay: 'bug_report',
  FileCode2: 'file_code',
  FileJson2: 'description',
  MoreHorizontal: 'more_horiz',
  Grid3X3: 'grid_view',
  ShieldCheck: 'verified_user',
  X: 'close',
  Bell: 'notifications',
  GitBranch: 'account_tree',
  Key: 'key',
  Lock: 'lock',
  CheckCheck: 'done_all',
  Mic: 'mic',
  Square: 'square',
  Pause: 'pause',
  Video: 'videocam',
  Download: 'download'
};

const GoogleTheme: Record<string, any> = {};
Object.entries(GOOGLE_ICON_MAP).forEach(([key, name]) => {
  GoogleTheme[key] = (props: any) => <MaterialIcon name={name} {...props} />;
});

export const ICON_THEMES: Record<string, any> = {
  'VS code': {
    MessageSquare, Code, Settings, Files, Play, ChevronRight, ChevronLeft, ChevronDown,
    Send, User, Terminal, Search, Plus, Copy, Check, Trash2, Edit3, Undo2, Redo2,
    ClipboardPaste, History, Save, RefreshCw, Maximize2, FolderOpen, ArrowUp, Wand2,
    Sparkles, Hash, Bug, FileText, Loader2, Users, Activity, Cpu, Zap, Box, 
    Paperclip, HelpCircle, ImageIcon, FileCode,
    FileJson, File, MoreVertical, ChevronDownIcon, ChevronRightIcon,
    ChevronUp, MoveDown, MoveUp, ArrowLeftToLine, ArrowRightToLine, Menu, Edit, Palette,
    SearchCode, CheckCircle2, CheckCircle, RefreshCcw, Grid3X3, ShieldCheck,
    X, Bell, GitBranch, Key, Lock, CheckCheck, Mic, Square, Pause, Video, Download
  },
  'ReversX v1': {
    MessageSquare: MessageCircle,
    Code: Code2,
    Settings: Cog,
    Files: Folder,
    Play: PlayCircle,
    ChevronRight, ChevronLeft, ChevronDown,
    Send, User: User2, Terminal: SquareTerminal, Search: SearchCode, Plus: PlusSquare,
    Copy, Check: CheckCircle2, Trash2: Trash, Edit3: Edit, Undo2, Redo2,
    ClipboardPaste, History, Save: SaveAll, RefreshCw: RefreshCcw, Maximize2: Maximize,
    FolderOpen: FolderClosed, ArrowUp: ArrowUpCircle, Wand2: Wand,
    Sparkles: Sparkle, Hash, Bug: BugPlay, FileText, Loader2, Users: Users2, 
    Activity, Cpu, Zap, Box, Paperclip, HelpCircle, ImageIcon, FileCode: FileCode2, FileJson: FileJson2, File, MoreVertical: MoreHorizontal,
    ChevronDownIcon: ChevronDown, ChevronRightIcon: ChevronRight,
    ChevronUp, MoveDown, MoveUp, ArrowLeftToLine, ArrowRightToLine, Menu, Edit, Palette,
    X, Bell, GitBranch, Key, Lock, CheckCheck, Mic, Square, Pause, Video, Download
  },
  'ReversX v2': {
    MessageSquare: (props: any) => <Codicon name="comment-discussion" {...props} />,
    Code: (props: any) => <Codicon name="code" {...props} />,
    Settings: (props: any) => <Codicon name="settings-gear" {...props} />,
    Files: (props: any) => <Codicon name="files" {...props} />,
    Play: (props: any) => <Codicon name="play" {...props} />,
    ChevronRight: (props: any) => <Codicon name="chevron-right" {...props} />,
    ChevronLeft: (props: any) => <Codicon name="chevron-left" {...props} />,
    ChevronDown: (props: any) => <Codicon name="chevron-down" {...props} />,
    ChevronUp: (props: any) => <Codicon name="chevron-up" {...props} />,
    Send: (props: any) => <Codicon name="send" {...props} />,
    User: (props: any) => <Codicon name="account" {...props} />,
    Terminal: (props: any) => <Codicon name="terminal" {...props} />,
    Search: (props: any) => <Codicon name="search" {...props} />,
    Plus: (props: any) => <Codicon name="add" {...props} />,
    Copy: (props: any) => <Codicon name="copy" {...props} />,
    Check: (props: any) => <Codicon name="check" {...props} />,
    Trash2: (props: any) => <Codicon name="trash" {...props} />,
    Edit3: (props: any) => <Codicon name="edit" {...props} />,
    Undo2: (props: any) => <Codicon name="discard" {...props} />,
    Redo2: (props: any) => <Codicon name="redo" {...props} />,
    ClipboardPaste: (props: any) => <Codicon name="clippy" {...props} />,
    History: (props: any) => <Codicon name="history" {...props} />,
    Save: (props: any) => <Codicon name="save" {...props} />,
    RefreshCw: (props: any) => <Codicon name="refresh" {...props} />,
    Maximize2: (props: any) => <Codicon name="screen-full" {...props} />,
    FolderOpen: (props: any) => <Codicon name="folder-opened" {...props} />,
    ArrowUp: (props: any) => <Codicon name="arrow-up" {...props} />,
    Wand2: (props: any) => <Codicon name="wand" {...props} />,
    Sparkles: (props: any) => <Codicon name="sparkle" {...props} />,
    Activity: (props: any) => <Codicon name="pulse" {...props} />,
    Cpu: (props: any) => <Codicon name="cpu" {...props} />,
    Zap: (props: any) => <Codicon name="zap" {...props} />,
    Box: (props: any) => <Codicon name="package" {...props} />,
    Hash: (props: any) => <Codicon name="symbol-keyword" {...props} />,
    Bug: (props: any) => <Codicon name="debug" {...props} />,
    FileText: (props: any) => <Codicon name="file-text" {...props} />,
    Loader2: (props: any) => <Codicon name="loading" className="animate-spin" {...props} />,
    Users: (props: any) => <Codicon name="organization" {...props} />,
    Paperclip: (props: any) => <Codicon name="attach" {...props} />,
    HelpCircle: (props: any) => <Codicon name="question" {...props} />,
    ImageIcon: (props: any) => <Codicon name="file-media" {...props} />,
    FileCode: (props: any) => <Codicon name="file-code" {...props} />,
    FileJson: (props: any) => <Codicon name="json" {...props} />,
    File: (props: any) => <Codicon name="file" {...props} />,
    MoreVertical: (props: any) => <Codicon name="more" {...props} />,
    ChevronDownIcon: (props: any) => <Codicon name="chevron-down" {...props} />,
    ChevronRightIcon: (props: any) => <Codicon name="chevron-right" {...props} />,
    MoveDown: (props: any) => <Codicon name="arrow-down" {...props} />,
    MoveUp: (props: any) => <Codicon name="arrow-up" {...props} />,
    ArrowLeftToLine: (props: any) => <Codicon name="arrow-left" {...props} />,
    ArrowRightToLine: (props: any) => <Codicon name="arrow-right" {...props} />,
    Menu: (props: any) => <Codicon name="menu" {...props} />,
    Edit: (props: any) => <Codicon name="edit" {...props} />,
    Palette: (props: any) => <Codicon name="symbol-color" {...props} />,
    SearchCode: (props: any) => <Codicon name="search-stop" {...props} />,
    CheckCircle2: (props: any) => <Codicon name="check" {...props} />,
    CheckCircle: (props: any) => <Codicon name="pass" {...props} />,
    RefreshCcw: (props: any) => <Codicon name="refresh" {...props} />,
    Grid3X3: (props: any) => <Codicon name="list-unordered" {...props} />,
    ShieldCheck: (props: any) => <Codicon name="shield" {...props} />,
    X: (props: any) => <Codicon name="close" {...props} />,
    Bell: (props: any) => <Codicon name="bell" {...props} />,
    GitBranch: (props: any) => <Codicon name="git-branch" {...props} />,
    Key: (props: any) => <Codicon name="key" {...props} />,
    Lock: (props: any) => <Codicon name="lock" {...props} />,
    CheckCheck: (props: any) => <Codicon name="check-all" {...props} />,
    Mic: (props: any) => <Codicon name="mic" {...props} />,
    Square: (props: any) => <Codicon name="primitive-square" {...props} />,
    Pause: (props: any) => <Codicon name="pause" {...props} />,
    Video: (props: any) => <Codicon name="video" {...props} />,
    Download: (props: any) => <Codicon name="download" {...props} />,
  },
  'Google': GoogleTheme,
  'Lucide Pro': {
    MessageSquare, Code: SquareTerminal, Settings: Cog, Files: FolderOpen, Play: PlayCircle,
    Send, User: Users, Terminal: SquareTerminal, Search: SearchCode, Plus: PlusSquare,
    Copy: Copy, Check: CheckCircle2, Trash2: Trash, Edit3: Edit, Undo2, Redo2,
    Save: SaveAll, RefreshCw: RefreshCcw, Maximize2: Maximize, FolderOpen: Folder, ArrowUp: ArrowUpCircle,
    FileCode: FileCode2, FileJson: FileJson2, File, ChevronDownIcon, ChevronRightIcon
  },
  'Minimal': {
    MessageSquare: MessageCircle, Code: Code2, Settings, Files: FolderClosed, Play,
    Send, User: User2, Terminal, Search, Plus, Copy, Check, Trash2, Edit3: Edit,
    Undo2, Redo2, Save, RefreshCw, Maximize2, FolderOpen, ArrowUp, FileCode, FileJson, File,
    ChevronDownIcon: ChevronDown, ChevronRightIcon: ChevronRight
  }
};

export const IconContext = React.createContext('ReversX v2');

export const useIcons = () => {
  const themeName = React.useContext(IconContext);
  const theme = ICON_THEMES[themeName] || ICON_THEMES['VS code'];
  // Merge with Default to ensure no missing icons
  return { ...ICON_THEMES['VS code'], ...theme };
};

