sonar.projectKey=remix-fork-of-reversx-3
sonar.projectName=Remix: Fork of ReversX 3
sonar.projectVersion=1.0
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json
sonar.exclusions=node_modules/**, dist/**, .github/**
